spring.application.name=githubLogger
spring.datasource.url=jdbc:postgresql://localhost:5432/github_logger
spring.datasource.username=DB_UserName
spring.datasource.password=DB_Password
spring.datasource.driver-class-name = org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.open-in-view=false

github.username=sid7152-glitch

api.url=https://api.github.com/users/enter_user/events
