# ==========================================
# Stage 1: Build the application using Maven
# ==========================================
FROM maven:3.9.6-eclipse-temurin-21-alpine AS builder
WORKDIR /app

# Copy the pom.xml and download dependencies first (helps with caching)
COPY pom.xml .
RUN mvn dependency:go-offline

# Copy the actual source code and package it into a .jar
COPY src ./src
RUN mvn clean package -DskipTests

# ==========================================
# Stage 2: Run the application
# ==========================================
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app

# Copy ONLY the generated .jar file from the 'builder' stage above
COPY --from=builder /app/target/*.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]

# postgresql://github_logger_db_wmml_user:BLSUNk7aYDQ8QCnlV7zvxZYgc1zgwL1O@dpg-d903pccm0tmc73ddqjq0-a/github_logger_db_wmml