# 1. The base environment (Java 17 is standard for modern Spring Boot)
FROM eclipse-temurin:21-jre-alpine

# 2. Transfer your generated .jar file into the container and rename it to 'app.jar'
COPY target/githubLogger-0.0.1-SNAPSHOT.jar app.jar

# 3. The command to run the application when the container starts
ENTRYPOINT ["java", "-jar", "/app.jar"]

# postgresql://github_logger_db_user:S24vcbLLO4lZabTJQXvcLXRZNhkSALP2@dpg-d903ksf7f7vs739p14bg-a/github_logger_db